export const SET_PERSON_COUNT = 'SET_PERSON_COUNT'
export const SET_MAX_PERSON_COUNT = 'SET_MAX_PERSON_COUNT'
export const INCREASE_PERSON_COUNT = 'INCREASE_PERSON_COUNT'
export const DECREASE_PERSON_COUNT = 'DECREASE_PERSON_COUNT'
